// Parse OEIS b-files in $LOCALAPPDATA/Temp and emit:
//   1. docs/long/<key>.js — full b-file digit string under window.LONG_DIGITS
//   2. console preview of each digit string
//
// Run from the repo root after downloading the b-files:
//   node scripts/parse_bfiles.js
//
// Sources are referenced in each generated file's banner comment.
const fs = require('fs');
const path = require('path');

const tmp = path.join(process.env.LOCALAPPDATA || process.env.TEMP || '/tmp', 'Temp');
// On git-bash /tmp maps to %LOCALAPPDATA%\Temp; fall back if needed
const tmpDir = fs.existsSync(tmp) ? tmp : (process.env.TEMP || '/tmp');

const SOURCES = [
  { id: 'A002193', file: 'sqrt2.txt',     strip: 1, key: 'sqrt2',     outKey: 'sqrt2',     label: '√2',       integer: '1',  base: 10 },
  { id: 'A001622', file: 'phi.txt',       strip: 1, key: 'phi',       outKey: 'phi',       label: 'φ',        integer: '1',  base: 10 },
  { id: 'A001113', file: 'e.txt',         strip: 1, key: 'e',         outKey: 'e',         label: 'e',        integer: '2',  base: 10 },
  { id: 'A002162', file: 'ln2.txt',       strip: 0, key: 'ln2',       outKey: 'ln2',       label: 'ln 2',     integer: '0',  base: 10 },
  { id: 'A002194', file: 'sqrt3.txt',     strip: 1, key: 'sqrt3',     outKey: 'sqrt3',     label: '√3',       integer: '1',  base: 10 },
  { id: 'A002163', file: 'sqrt5.txt',     strip: 1, key: 'sqrt5',     outKey: 'sqrt5',     label: '√5',       integer: '2',  base: 10 },
  { id: 'A007524', file: 'log10_2.txt',   strip: 0, key: 'log10_2',   outKey: 'log10_2',   label: 'log₁₀ 2',  integer: '0',  base: 10 },
  { id: 'A002388', file: 'pi_sq.txt',     strip: 1, key: 'pi_sq',     outKey: 'pi-squared', label: 'π²',       integer: '9',  base: 10 },
  { id: 'A001620', file: 'euler_mascheroni.txt', strip: 0, key: 'euler_mascheroni', outKey: 'euler-mascheroni', label: 'γ (Euler–Mascheroni)', integer: '0', base: 10 },
  { id: 'A013661', file: 'zeta2.txt',     strip: 1, key: 'zeta2',     outKey: 'zeta2',     label: 'ζ(2) = π²/6', integer: '1', base: 10 },
  { id: 'A004601', file: 'pi_binary.txt', strip: 2, key: 'pi_binary', outKey: 'pi-binary', label: 'π in binary', integer: '11', base: 2  },
  // A062964 stores each hex digit as a decimal int 0-15; map to 0-9A-F.
  { id: 'A062964', file: 'pi_hex.txt',    strip: 1, key: 'pi_hex',    outKey: 'pi-hex',    label: 'π in hex', integer: '3',  base: 16 },
];

const OUT_DIR = path.join(__dirname, '..', 'docs', 'long');
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

for (const src of SOURCES) {
  const filePath = path.join(tmpDir, src.file);
  if (!fs.existsSync(filePath)) {
    console.error(`MISSING: ${filePath}`);
    continue;
  }
  const text = fs.readFileSync(filePath, 'utf8');
  const tokens = [];
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const parts = trimmed.split(/\s+/);
    if (parts.length < 2) continue;
    const n = parseInt(parts[1], 10);
    if (Number.isNaN(n) || n < 0 || n >= src.base) {
      console.error(`OUT-OF-RANGE digit "${parts[1]}" in ${src.key}; aborting`);
      process.exit(2);
    }
    tokens.push(n.toString(src.base).toUpperCase());
  }
  const all = tokens.join('');
  if (src.strip > 0) {
    const lead = all.slice(0, src.strip);
    if (lead !== src.integer) {
      console.error(`MISMATCH ${src.key}: expected integer "${src.integer}", got "${lead}"`);
    }
  }
  const digits = all.slice(src.strip);
  const outPath = path.join(OUT_DIR, `${src.outKey}.js`);
  const banner =
    `// Long decimal expansion of ${src.label}, post-decimal-point.\n` +
    `// Source: https://oeis.org/${src.id}/b${src.id.slice(1).toLowerCase()}.txt (${digits.length} digits)\n` +
    `// Generated by scripts/parse_bfiles.js — do not edit by hand.\n`;
  const body = `(window.LONG_DIGITS = window.LONG_DIGITS || {})[${JSON.stringify(src.outKey)}] = ${JSON.stringify(digits)};\n`;
  fs.writeFileSync(outPath, banner + body);
  console.log(`${src.outKey}: ${digits.length} digits → docs/long/${src.outKey}.js`);
}
